-- Setup UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Core Platform Tables

CREATE TYPE plan_tier AS ENUM ('free', 'pro', 'team');

CREATE TABLE users (
    id TEXT PRIMARY KEY, -- Changed to TEXT for Clerk compatibility
    email TEXT UNIQUE NOT NULL,
    name TEXT,
    plan_tier plan_tier DEFAULT 'free'::plan_tier,
    stripe_customer_id TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE projects (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, -- Changed to TEXT
    name TEXT NOT NULL,
    target_url TEXT NOT NULL,
    requires_auth BOOLEAN DEFAULT false,
    auth_credentials TEXT, -- Encrypted JSON
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE (user_id, target_url) -- Composite unique for cleaner upserts
);

-- 2. Testing Configuration Tables

CREATE TYPE tech_literacy AS ENUM ('low', 'medium', 'high');

CREATE TABLE persona_configs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    project_id UUID REFERENCES projects(id) ON DELETE CASCADE, -- Made optional for "Library" personas
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, -- Direct link for library
    name TEXT NOT NULL,
    age_range TEXT,
    geolocation TEXT,
    tech_literacy tech_literacy DEFAULT 'medium'::tech_literacy,
    goal_prompt TEXT NOT NULL,
    ai_system_prompt TEXT, -- Expanded profile generated by LLM
    domain_familiarity TEXT, -- Added field
    persona_count INTEGER DEFAULT 1, -- Number of personas to deploy
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TYPE test_run_status AS ENUM ('pending', 'running', 'completed', 'failed');

CREATE TABLE test_runs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    status test_run_status DEFAULT 'pending'::test_run_status,
    started_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Session & Execution Tables

CREATE TYPE session_status AS ENUM ('queued', 'running', 'completed', 'abandoned', 'error');

CREATE TABLE persona_sessions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    test_run_id UUID NOT NULL REFERENCES test_runs(id) ON DELETE CASCADE,
    persona_config_id UUID NOT NULL REFERENCES persona_configs(id) ON DELETE CASCADE,
    status session_status DEFAULT 'queued'::session_status,
    exit_reason TEXT,
    started_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TYPE emotion_tag AS ENUM ('neutral', 'confusion', 'frustration', 'delight');

CREATE TABLE session_logs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    session_id UUID NOT NULL REFERENCES persona_sessions(id) ON DELETE CASCADE,
    step_number INTEGER NOT NULL,
    current_url TEXT NOT NULL,
    screenshot_url TEXT,
    emotion_tag emotion_tag DEFAULT 'neutral'::emotion_tag,
    emotion_score INTEGER CHECK (emotion_score >= 1 AND emotion_score <= 10),
    inner_monologue TEXT,
    action_taken JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Aggregation Tables

CREATE TABLE reports (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    test_run_id UUID NOT NULL UNIQUE REFERENCES test_runs(id) ON DELETE CASCADE,
    product_opportunity_score INTEGER CHECK (product_opportunity_score >= 0 AND product_opportunity_score <= 100),
    executive_summary TEXT,
    funnel_completion_rate DECIMAL(5,2),
    heatmap_data_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Set up Row Level Security (RLS)

-- Users
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own profile" ON users FOR SELECT USING (id = auth.jwt() ->> 'sub' OR id = current_setting('request.jwt.claims', true)::json ->> 'sub'); 
-- Note: Supabase auth.uid() won't work easily with external JWTs unless configured. 
-- For now, we will handle this via service role or custom policies if needed. 
-- Actually, since we use the Service Role for syncing and 'auth()' from clerk in server actions, 
-- We can simplify the RLS if the app uses server-side fetching predominantly.
CREATE POLICY "Users can update own profile" ON users FOR UPDATE USING (id = auth.jwt() ->> 'sub');

-- Projects
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own projects" ON projects FOR SELECT USING (user_id = auth.jwt() ->> 'sub');
CREATE POLICY "Users can insert own projects" ON projects FOR INSERT WITH CHECK (user_id = auth.jwt() ->> 'sub');
CREATE POLICY "Users can update own projects" ON projects FOR UPDATE USING (user_id = auth.jwt() ->> 'sub');
CREATE POLICY "Users can delete own projects" ON projects FOR DELETE USING (user_id = auth.jwt() ->> 'sub');

-- Test Runs
ALTER TABLE test_runs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own test runs through projects" ON test_runs FOR SELECT USING (
    EXISTS (SELECT 1 FROM projects WHERE projects.id = test_runs.project_id AND projects.user_id = auth.jwt() ->> 'sub')
);
CREATE POLICY "Users can insert own test runs" ON test_runs FOR INSERT WITH CHECK (
    EXISTS (SELECT 1 FROM projects WHERE projects.id = project_id AND projects.user_id = auth.jwt() ->> 'sub')
);

-- Persona Configs
ALTER TABLE persona_configs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own persona configs" ON persona_configs FOR SELECT USING (
    user_id = auth.jwt() ->> 'sub'
);
CREATE POLICY "Users can insert own persona configs" ON persona_configs FOR INSERT WITH CHECK (
    user_id = auth.jwt() ->> 'sub'
);

-- Persona Sessions
ALTER TABLE persona_sessions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own persona sessions" ON persona_sessions FOR SELECT USING (
    EXISTS (
        SELECT 1 FROM test_runs 
        JOIN projects ON projects.id = test_runs.project_id 
        WHERE test_runs.id = persona_sessions.test_run_id AND projects.user_id = auth.jwt() ->> 'sub'
    )
);
CREATE POLICY "Users can insert own persona sessions" ON persona_sessions FOR INSERT WITH CHECK (
    EXISTS (
        SELECT 1 FROM test_runs 
        JOIN projects ON projects.id = test_runs.project_id 
        WHERE test_runs.id = persona_sessions.test_run_id AND projects.user_id = auth.jwt() ->> 'sub'
    )
);

-- Session Logs
ALTER TABLE session_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own session logs" ON session_logs FOR SELECT USING (
    EXISTS (
        SELECT 1 FROM persona_sessions
        JOIN test_runs ON test_runs.id = persona_sessions.test_run_id
        JOIN projects ON projects.id = test_runs.project_id
        WHERE persona_sessions.id = session_logs.session_id AND projects.user_id = auth.jwt() ->> 'sub'
    )
);

-- Reports
ALTER TABLE reports ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own reports" ON reports FOR SELECT USING (
    EXISTS (
        SELECT 1 FROM test_runs 
        JOIN projects ON projects.id = test_runs.project_id 
        WHERE test_runs.id = reports.test_run_id AND projects.user_id = auth.jwt() ->> 'sub'
    )
);
